using IOMS.DAL.Entities;

namespace IOMS.DAL;

// Kezdeti (fejlesztői) adatok; a Configurations mappa osztályai adják át a HasData-nak.
// Minden hívás új példányokat ad, hogy az EF ne ossza meg őket entitások között.
internal static class SeedData
{
    public static Product[] Products =>
    [
        new Product { Id = 1, Name = "Logitech MX Master 3S egér", SKU = "PER-MX3S", Category = "Perifériák", MinStockLevel = 10, Price = 39990m },
        new Product { Id = 2, Name = "Keychron K2 billentyűzet", SKU = "PER-K2", Category = "Perifériák", MinStockLevel = 8, Price = 34990m },
        new Product { Id = 3, Name = "Dell P2723D 27\" monitor", SKU = "PER-P2723D", Category = "Perifériák", MinStockLevel = 5, Price = 104990m },
        new Product { Id = 4, Name = "Samsung 990 Pro 1TB SSD", SKU = "STO-990P-1T", Category = "Tárolóeszközök", MinStockLevel = 10, Price = 49990m },
        new Product { Id = 5, Name = "WD Red Plus 4TB HDD", SKU = "STO-WDRP-4T", Category = "Tárolóeszközök", MinStockLevel = 6, Price = 44990m },
        new Product { Id = 6, Name = "SanDisk Ultra 128GB pendrive", SKU = "STO-SDU-128", Category = "Tárolóeszközök", MinStockLevel = 15, Price = 5990m },
        new Product { Id = 7, Name = "TP-Link Archer AX55 router", SKU = "NET-AX55", Category = "Hálózati eszközök", MinStockLevel = 5, Price = 32990m },
        new Product { Id = 8, Name = "Ubiquiti UniFi Switch Lite 8", SKU = "NET-USL8", Category = "Hálózati eszközök", MinStockLevel = 4, Price = 42990m },
        new Product { Id = 9, Name = "Logitech K380 billentyűzet", SKU = "PER-K380", Category = "Perifériák", MinStockLevel = 10, Price = 14990m },
        new Product { Id = 10, Name = "Razer DeathAdder V3 egér", SKU = "PER-DAV3", Category = "Perifériák", MinStockLevel = 6, Price = 29990m },
        new Product { Id = 11, Name = "LG 27GP850 27\" monitor", SKU = "PER-27GP850", Category = "Perifériák", MinStockLevel = 3, Price = 159990m },
        new Product { Id = 12, Name = "Kingston NV2 1TB SSD", SKU = "STO-NV2-1T", Category = "Tárolóeszközök", MinStockLevel = 15, Price = 24990m },
        new Product { Id = 13, Name = "Seagate IronWolf 8TB HDD", SKU = "STO-IW-8T", Category = "Tárolóeszközök", MinStockLevel = 4, Price = 89990m },
        new Product { Id = 14, Name = "TP-Link TL-SG108 switch", SKU = "NET-SG108", Category = "Hálózati eszközök", MinStockLevel = 8, Price = 9990m },
        new Product { Id = 15, Name = "Ubiquiti U6 Lite access point", SKU = "NET-U6L", Category = "Hálózati eszközök", MinStockLevel = 5, Price = 44990m },
        new Product { Id = 16, Name = "UGREEN USB-C hub 7 az 1-ben", SKU = "KAB-UGH7", Category = "Kábelek és adapterek", MinStockLevel = 20, Price = 12990m },
        new Product { Id = 17, Name = "Cat6 patchkábel 2 m", SKU = "KAB-CAT6-2", Category = "Kábelek és adapterek", MinStockLevel = 100, Price = 990m },
        new Product { Id = 18, Name = "HDMI 2.1 kábel 2 m", SKU = "KAB-HDMI21", Category = "Kábelek és adapterek", MinStockLevel = 30, Price = 3990m },
        new Product { Id = 19, Name = "Corsair Vengeance 32GB DDR5", SKU = "ALK-CV32D5", Category = "Számítógép-alkatrészek", MinStockLevel = 6, Price = 39990m },
        new Product { Id = 20, Name = "AMD Ryzen 7 7700X processzor", SKU = "ALK-R77700X", Category = "Számítógép-alkatrészek", MinStockLevel = 3, Price = 109990m },
    ];

    public static Customer[] Customers =>
    [
        new Customer { Id = 1, Name = "Kovács Anna", Email = "anna.kovacs@example.com", Phone = "+36 30 111 2222" },
        new Customer { Id = 2, Name = "Nagy Péter", Email = "peter.nagy@example.com", Phone = "+36 20 333 4444" },
        new Customer { Id = 3, Name = "Szabó és Társa Kft.", Email = "beszerzes@szabo-kft.example.com" },
        new Customer { Id = 4, Name = "Tóth Gábor", Email = "gabor.toth@example.com", Phone = "+36 70 555 0101" },
        new Customer { Id = 5, Name = "Horváth Eszter", Email = "eszter.horvath@example.com", Phone = "+36 30 222 3344" },
        new Customer { Id = 6, Name = "Varga Bence", Email = "bence.varga@example.com" },
        new Customer { Id = 7, Name = "Kiss és Fia Bt.", Email = "iroda@kissesfia.example.com", Phone = "+36 1 444 2020" },
        new Customer { Id = 8, Name = "Molnár Réka", Email = "reka.molnar@example.com", Phone = "+36 20 987 6543" },
        new Customer { Id = 9, Name = "Németh László", Email = "laszlo.nemeth@example.com" },
        new Customer { Id = 10, Name = "DigitalPro Zrt.", Email = "beszerzes@digitalpro.example.com", Phone = "+36 1 777 8899" },
        new Customer { Id = 11, Name = "Farkas Dóra", Email = "dora.farkas@example.com", Phone = "+36 30 765 4321" },
        new Customer { Id = 12, Name = "Balogh Informatika Kft.", Email = "info@balogh-it.example.com", Phone = "+36 62 333 1100" },
    ];

    public static Supplier[] Suppliers =>
    [
        new Supplier { Id = 1, Name = "TechDistri Kft.", Email = "rendeles@techdistri.example.com", Phone = "+36 1 555 1000" },
        new Supplier { Id = 2, Name = "NetParts Zrt.", Email = "sales@netparts.example.com" },
        new Supplier { Id = 3, Name = "Kábelvilág Kft.", Email = "rendeles@kabelvilag.example.com", Phone = "+36 1 600 2500" },
        new Supplier { Id = 4, Name = "AlkatrészPont Bt.", Email = "info@alkatreszpont.example.com" },
    ];

    public static Warehouse[] Warehouses =>
    [
        new Warehouse { Id = 1, Name = "Budapesti központi raktár", Address = "1117 Budapest, Példa utca 1.", Capacity = 5000, Latitude = 47.4730, Longitude = 19.0530 },
        new Warehouse { Id = 2, Name = "Debreceni raktár", Address = "4031 Debrecen, Minta út 12.", Capacity = 2000, Latitude = 47.5316, Longitude = 21.6273 },
        new Warehouse { Id = 3, Name = "Győri raktár", Address = "9027 Győr, Ipari park 5.", Capacity = 3000, Latitude = 47.6875, Longitude = 17.6504 },
        new Warehouse { Id = 4, Name = "Szegedi raktár", Address = "6728 Szeged, Logisztikai út 3.", Capacity = 1500, Latitude = 46.2530, Longitude = 20.1414 },
        new Warehouse { Id = 5, Name = "Pécsi raktár", Address = "7630 Pécs, Raktár utca 9.", Capacity = 1200, Latitude = 46.0727, Longitude = 18.2323 },
    ];

    public static CustomerOrder[] CustomerOrders =>
    [
        new CustomerOrder { Id = 1, CustomerId = 1, OrderDate = new DateTime(2026, 9, 1, 9, 30, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new CustomerOrder { Id = 2, CustomerId = 2, OrderDate = new DateTime(2026, 9, 10, 14, 5, 0, DateTimeKind.Utc), Status = OrderStatus.Shipped },
        new CustomerOrder { Id = 3, CustomerId = 3, OrderDate = new DateTime(2026, 9, 20, 11, 0, 0, DateTimeKind.Utc), Status = OrderStatus.Pending },
        new CustomerOrder { Id = 4, CustomerId = 1, OrderDate = new DateTime(2026, 9, 22, 16, 45, 0, DateTimeKind.Utc), Status = OrderStatus.Cancelled },
        new CustomerOrder { Id = 5, CustomerId = 1, OrderDate = new DateTime(2026, 8, 1, 17, 45, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new CustomerOrder { Id = 6, CustomerId = 5, OrderDate = new DateTime(2026, 8, 2, 14, 15, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new CustomerOrder { Id = 7, CustomerId = 2, OrderDate = new DateTime(2026, 8, 4, 11, 30, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new CustomerOrder { Id = 8, CustomerId = 7, OrderDate = new DateTime(2026, 8, 5, 13, 0, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new CustomerOrder { Id = 9, CustomerId = 5, OrderDate = new DateTime(2026, 8, 7, 9, 0, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new CustomerOrder { Id = 10, CustomerId = 1, OrderDate = new DateTime(2026, 8, 8, 14, 30, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new CustomerOrder { Id = 11, CustomerId = 4, OrderDate = new DateTime(2026, 8, 9, 17, 15, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new CustomerOrder { Id = 12, CustomerId = 9, OrderDate = new DateTime(2026, 8, 11, 8, 15, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new CustomerOrder { Id = 13, CustomerId = 2, OrderDate = new DateTime(2026, 8, 12, 11, 15, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new CustomerOrder { Id = 14, CustomerId = 12, OrderDate = new DateTime(2026, 8, 14, 15, 15, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new CustomerOrder { Id = 15, CustomerId = 5, OrderDate = new DateTime(2026, 8, 15, 11, 15, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new CustomerOrder { Id = 16, CustomerId = 12, OrderDate = new DateTime(2026, 8, 16, 8, 30, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new CustomerOrder { Id = 17, CustomerId = 4, OrderDate = new DateTime(2026, 8, 17, 17, 30, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new CustomerOrder { Id = 18, CustomerId = 1, OrderDate = new DateTime(2026, 8, 19, 10, 0, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new CustomerOrder { Id = 19, CustomerId = 2, OrderDate = new DateTime(2026, 8, 20, 10, 30, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new CustomerOrder { Id = 20, CustomerId = 5, OrderDate = new DateTime(2026, 8, 22, 16, 30, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new CustomerOrder { Id = 21, CustomerId = 9, OrderDate = new DateTime(2026, 8, 24, 10, 15, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new CustomerOrder { Id = 22, CustomerId = 5, OrderDate = new DateTime(2026, 8, 25, 11, 30, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new CustomerOrder { Id = 23, CustomerId = 8, OrderDate = new DateTime(2026, 8, 26, 13, 0, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new CustomerOrder { Id = 24, CustomerId = 10, OrderDate = new DateTime(2026, 8, 28, 8, 15, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new CustomerOrder { Id = 25, CustomerId = 10, OrderDate = new DateTime(2026, 8, 28, 18, 15, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new CustomerOrder { Id = 26, CustomerId = 10, OrderDate = new DateTime(2026, 8, 30, 10, 30, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new CustomerOrder { Id = 27, CustomerId = 11, OrderDate = new DateTime(2026, 9, 1, 13, 45, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new CustomerOrder { Id = 28, CustomerId = 12, OrderDate = new DateTime(2026, 9, 2, 13, 15, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new CustomerOrder { Id = 29, CustomerId = 11, OrderDate = new DateTime(2026, 9, 3, 14, 15, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new CustomerOrder { Id = 30, CustomerId = 4, OrderDate = new DateTime(2026, 9, 4, 16, 30, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new CustomerOrder { Id = 31, CustomerId = 7, OrderDate = new DateTime(2026, 9, 6, 9, 15, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new CustomerOrder { Id = 32, CustomerId = 5, OrderDate = new DateTime(2026, 9, 7, 16, 0, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new CustomerOrder { Id = 33, CustomerId = 11, OrderDate = new DateTime(2026, 9, 9, 12, 0, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new CustomerOrder { Id = 34, CustomerId = 5, OrderDate = new DateTime(2026, 9, 10, 12, 0, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new CustomerOrder { Id = 35, CustomerId = 8, OrderDate = new DateTime(2026, 9, 12, 13, 15, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new CustomerOrder { Id = 36, CustomerId = 7, OrderDate = new DateTime(2026, 9, 13, 16, 0, 0, DateTimeKind.Utc), Status = OrderStatus.Cancelled },
        new CustomerOrder { Id = 37, CustomerId = 12, OrderDate = new DateTime(2026, 9, 15, 9, 0, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new CustomerOrder { Id = 38, CustomerId = 2, OrderDate = new DateTime(2026, 9, 16, 8, 45, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new CustomerOrder { Id = 39, CustomerId = 3, OrderDate = new DateTime(2026, 9, 17, 17, 15, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new CustomerOrder { Id = 40, CustomerId = 5, OrderDate = new DateTime(2026, 9, 19, 11, 30, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new CustomerOrder { Id = 41, CustomerId = 8, OrderDate = new DateTime(2026, 9, 19, 14, 0, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new CustomerOrder { Id = 42, CustomerId = 4, OrderDate = new DateTime(2026, 9, 21, 12, 0, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new CustomerOrder { Id = 43, CustomerId = 1, OrderDate = new DateTime(2026, 9, 23, 11, 15, 0, DateTimeKind.Utc), Status = OrderStatus.Cancelled },
        new CustomerOrder { Id = 44, CustomerId = 12, OrderDate = new DateTime(2026, 9, 25, 8, 0, 0, DateTimeKind.Utc), Status = OrderStatus.Shipped },
        new CustomerOrder { Id = 45, CustomerId = 9, OrderDate = new DateTime(2026, 9, 25, 15, 45, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new CustomerOrder { Id = 46, CustomerId = 4, OrderDate = new DateTime(2026, 9, 27, 14, 15, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new CustomerOrder { Id = 47, CustomerId = 1, OrderDate = new DateTime(2026, 9, 28, 9, 45, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new CustomerOrder { Id = 48, CustomerId = 6, OrderDate = new DateTime(2026, 9, 30, 8, 0, 0, DateTimeKind.Utc), Status = OrderStatus.Shipped },
        new CustomerOrder { Id = 49, CustomerId = 11, OrderDate = new DateTime(2026, 10, 1, 10, 0, 0, DateTimeKind.Utc), Status = OrderStatus.Pending },
        new CustomerOrder { Id = 50, CustomerId = 9, OrderDate = new DateTime(2026, 10, 2, 18, 30, 0, DateTimeKind.Utc), Status = OrderStatus.Pending },
    ];

    public static CustomerOrderItem[] CustomerOrderItems =>
    [
        new CustomerOrderItem { Id = 1, CustomerOrderId = 1, ProductId = 1, Quantity = 2, UnitPrice = 39990m },
        new CustomerOrderItem { Id = 2, CustomerOrderId = 1, ProductId = 4, Quantity = 1, UnitPrice = 49990m },
        new CustomerOrderItem { Id = 3, CustomerOrderId = 2, ProductId = 7, Quantity = 1, UnitPrice = 32990m },
        new CustomerOrderItem { Id = 4, CustomerOrderId = 2, ProductId = 6, Quantity = 5, UnitPrice = 5990m },
        new CustomerOrderItem { Id = 5, CustomerOrderId = 3, ProductId = 3, Quantity = 3, UnitPrice = 104990m },
        new CustomerOrderItem { Id = 6, CustomerOrderId = 3, ProductId = 2, Quantity = 3, UnitPrice = 34990m },
        new CustomerOrderItem { Id = 7, CustomerOrderId = 3, ProductId = 8, Quantity = 2, UnitPrice = 42990m },
        new CustomerOrderItem { Id = 8, CustomerOrderId = 4, ProductId = 5, Quantity = 2, UnitPrice = 44990m },
        new CustomerOrderItem { Id = 9, CustomerOrderId = 5, ProductId = 11, Quantity = 3, UnitPrice = 159990m },
        new CustomerOrderItem { Id = 10, CustomerOrderId = 5, ProductId = 14, Quantity = 2, UnitPrice = 9990m },
        new CustomerOrderItem { Id = 11, CustomerOrderId = 5, ProductId = 8, Quantity = 1, UnitPrice = 42990m },
        new CustomerOrderItem { Id = 12, CustomerOrderId = 6, ProductId = 2, Quantity = 3, UnitPrice = 34990m },
        new CustomerOrderItem { Id = 13, CustomerOrderId = 6, ProductId = 11, Quantity = 2, UnitPrice = 159990m },
        new CustomerOrderItem { Id = 14, CustomerOrderId = 6, ProductId = 14, Quantity = 2, UnitPrice = 9990m },
        new CustomerOrderItem { Id = 15, CustomerOrderId = 7, ProductId = 17, Quantity = 12, UnitPrice = 990m },
        new CustomerOrderItem { Id = 16, CustomerOrderId = 7, ProductId = 12, Quantity = 1, UnitPrice = 24990m },
        new CustomerOrderItem { Id = 17, CustomerOrderId = 7, ProductId = 10, Quantity = 3, UnitPrice = 29990m },
        new CustomerOrderItem { Id = 18, CustomerOrderId = 8, ProductId = 8, Quantity = 2, UnitPrice = 42990m },
        new CustomerOrderItem { Id = 19, CustomerOrderId = 8, ProductId = 5, Quantity = 1, UnitPrice = 44990m },
        new CustomerOrderItem { Id = 20, CustomerOrderId = 8, ProductId = 7, Quantity = 2, UnitPrice = 32990m },
        new CustomerOrderItem { Id = 21, CustomerOrderId = 9, ProductId = 2, Quantity = 2, UnitPrice = 34990m },
        new CustomerOrderItem { Id = 22, CustomerOrderId = 9, ProductId = 20, Quantity = 1, UnitPrice = 109990m },
        new CustomerOrderItem { Id = 23, CustomerOrderId = 10, ProductId = 5, Quantity = 3, UnitPrice = 44990m },
        new CustomerOrderItem { Id = 24, CustomerOrderId = 11, ProductId = 6, Quantity = 1, UnitPrice = 5990m },
        new CustomerOrderItem { Id = 25, CustomerOrderId = 11, ProductId = 8, Quantity = 1, UnitPrice = 42990m },
        new CustomerOrderItem { Id = 26, CustomerOrderId = 12, ProductId = 5, Quantity = 2, UnitPrice = 44990m },
        new CustomerOrderItem { Id = 27, CustomerOrderId = 12, ProductId = 13, Quantity = 2, UnitPrice = 89990m },
        new CustomerOrderItem { Id = 28, CustomerOrderId = 12, ProductId = 6, Quantity = 1, UnitPrice = 5990m },
        new CustomerOrderItem { Id = 29, CustomerOrderId = 13, ProductId = 5, Quantity = 2, UnitPrice = 44990m },
        new CustomerOrderItem { Id = 30, CustomerOrderId = 13, ProductId = 20, Quantity = 2, UnitPrice = 109990m },
        new CustomerOrderItem { Id = 31, CustomerOrderId = 14, ProductId = 10, Quantity = 3, UnitPrice = 29990m },
        new CustomerOrderItem { Id = 32, CustomerOrderId = 14, ProductId = 6, Quantity = 3, UnitPrice = 5990m },
        new CustomerOrderItem { Id = 33, CustomerOrderId = 15, ProductId = 14, Quantity = 2, UnitPrice = 9990m },
        new CustomerOrderItem { Id = 34, CustomerOrderId = 15, ProductId = 11, Quantity = 1, UnitPrice = 159990m },
        new CustomerOrderItem { Id = 35, CustomerOrderId = 15, ProductId = 15, Quantity = 2, UnitPrice = 44990m },
        new CustomerOrderItem { Id = 36, CustomerOrderId = 16, ProductId = 15, Quantity = 2, UnitPrice = 44990m },
        new CustomerOrderItem { Id = 37, CustomerOrderId = 16, ProductId = 19, Quantity = 3, UnitPrice = 39990m },
        new CustomerOrderItem { Id = 38, CustomerOrderId = 16, ProductId = 16, Quantity = 3, UnitPrice = 12990m },
        new CustomerOrderItem { Id = 39, CustomerOrderId = 17, ProductId = 7, Quantity = 2, UnitPrice = 32990m },
        new CustomerOrderItem { Id = 40, CustomerOrderId = 18, ProductId = 16, Quantity = 2, UnitPrice = 12990m },
        new CustomerOrderItem { Id = 41, CustomerOrderId = 18, ProductId = 20, Quantity = 2, UnitPrice = 109990m },
        new CustomerOrderItem { Id = 42, CustomerOrderId = 19, ProductId = 10, Quantity = 3, UnitPrice = 29990m },
        new CustomerOrderItem { Id = 43, CustomerOrderId = 19, ProductId = 11, Quantity = 3, UnitPrice = 159990m },
        new CustomerOrderItem { Id = 44, CustomerOrderId = 19, ProductId = 9, Quantity = 3, UnitPrice = 14990m },
        new CustomerOrderItem { Id = 45, CustomerOrderId = 20, ProductId = 15, Quantity = 2, UnitPrice = 44990m },
        new CustomerOrderItem { Id = 46, CustomerOrderId = 20, ProductId = 18, Quantity = 14, UnitPrice = 3990m },
        new CustomerOrderItem { Id = 47, CustomerOrderId = 20, ProductId = 17, Quantity = 9, UnitPrice = 990m },
        new CustomerOrderItem { Id = 48, CustomerOrderId = 21, ProductId = 2, Quantity = 1, UnitPrice = 34990m },
        new CustomerOrderItem { Id = 49, CustomerOrderId = 21, ProductId = 18, Quantity = 19, UnitPrice = 3990m },
        new CustomerOrderItem { Id = 50, CustomerOrderId = 21, ProductId = 10, Quantity = 2, UnitPrice = 29990m },
        new CustomerOrderItem { Id = 51, CustomerOrderId = 22, ProductId = 1, Quantity = 1, UnitPrice = 39990m },
        new CustomerOrderItem { Id = 52, CustomerOrderId = 22, ProductId = 12, Quantity = 1, UnitPrice = 24990m },
        new CustomerOrderItem { Id = 53, CustomerOrderId = 23, ProductId = 14, Quantity = 3, UnitPrice = 9990m },
        new CustomerOrderItem { Id = 54, CustomerOrderId = 23, ProductId = 1, Quantity = 1, UnitPrice = 39990m },
        new CustomerOrderItem { Id = 55, CustomerOrderId = 23, ProductId = 6, Quantity = 1, UnitPrice = 5990m },
        new CustomerOrderItem { Id = 56, CustomerOrderId = 24, ProductId = 19, Quantity = 1, UnitPrice = 39990m },
        new CustomerOrderItem { Id = 57, CustomerOrderId = 25, ProductId = 18, Quantity = 13, UnitPrice = 3990m },
        new CustomerOrderItem { Id = 58, CustomerOrderId = 25, ProductId = 1, Quantity = 2, UnitPrice = 39990m },
        new CustomerOrderItem { Id = 59, CustomerOrderId = 26, ProductId = 11, Quantity = 3, UnitPrice = 159990m },
        new CustomerOrderItem { Id = 60, CustomerOrderId = 26, ProductId = 19, Quantity = 3, UnitPrice = 39990m },
        new CustomerOrderItem { Id = 61, CustomerOrderId = 27, ProductId = 1, Quantity = 2, UnitPrice = 39990m },
        new CustomerOrderItem { Id = 62, CustomerOrderId = 28, ProductId = 8, Quantity = 3, UnitPrice = 42990m },
        new CustomerOrderItem { Id = 63, CustomerOrderId = 29, ProductId = 7, Quantity = 3, UnitPrice = 32990m },
        new CustomerOrderItem { Id = 64, CustomerOrderId = 30, ProductId = 7, Quantity = 3, UnitPrice = 32990m },
        new CustomerOrderItem { Id = 65, CustomerOrderId = 31, ProductId = 8, Quantity = 1, UnitPrice = 42990m },
        new CustomerOrderItem { Id = 66, CustomerOrderId = 31, ProductId = 6, Quantity = 1, UnitPrice = 5990m },
        new CustomerOrderItem { Id = 67, CustomerOrderId = 32, ProductId = 13, Quantity = 1, UnitPrice = 89990m },
        new CustomerOrderItem { Id = 68, CustomerOrderId = 32, ProductId = 15, Quantity = 3, UnitPrice = 44990m },
        new CustomerOrderItem { Id = 69, CustomerOrderId = 32, ProductId = 11, Quantity = 2, UnitPrice = 159990m },
        new CustomerOrderItem { Id = 70, CustomerOrderId = 33, ProductId = 18, Quantity = 11, UnitPrice = 3990m },
        new CustomerOrderItem { Id = 71, CustomerOrderId = 33, ProductId = 16, Quantity = 3, UnitPrice = 12990m },
        new CustomerOrderItem { Id = 72, CustomerOrderId = 33, ProductId = 4, Quantity = 1, UnitPrice = 49990m },
        new CustomerOrderItem { Id = 73, CustomerOrderId = 34, ProductId = 1, Quantity = 3, UnitPrice = 39990m },
        new CustomerOrderItem { Id = 74, CustomerOrderId = 35, ProductId = 14, Quantity = 1, UnitPrice = 9990m },
        new CustomerOrderItem { Id = 75, CustomerOrderId = 36, ProductId = 6, Quantity = 2, UnitPrice = 5990m },
        new CustomerOrderItem { Id = 76, CustomerOrderId = 36, ProductId = 5, Quantity = 1, UnitPrice = 44990m },
        new CustomerOrderItem { Id = 77, CustomerOrderId = 37, ProductId = 11, Quantity = 2, UnitPrice = 159990m },
        new CustomerOrderItem { Id = 78, CustomerOrderId = 37, ProductId = 17, Quantity = 18, UnitPrice = 990m },
        new CustomerOrderItem { Id = 79, CustomerOrderId = 37, ProductId = 15, Quantity = 1, UnitPrice = 44990m },
        new CustomerOrderItem { Id = 80, CustomerOrderId = 38, ProductId = 4, Quantity = 3, UnitPrice = 49990m },
        new CustomerOrderItem { Id = 81, CustomerOrderId = 38, ProductId = 18, Quantity = 11, UnitPrice = 3990m },
        new CustomerOrderItem { Id = 82, CustomerOrderId = 38, ProductId = 20, Quantity = 3, UnitPrice = 109990m },
        new CustomerOrderItem { Id = 83, CustomerOrderId = 39, ProductId = 4, Quantity = 3, UnitPrice = 49990m },
        new CustomerOrderItem { Id = 84, CustomerOrderId = 40, ProductId = 2, Quantity = 2, UnitPrice = 34990m },
        new CustomerOrderItem { Id = 85, CustomerOrderId = 40, ProductId = 7, Quantity = 1, UnitPrice = 32990m },
        new CustomerOrderItem { Id = 86, CustomerOrderId = 41, ProductId = 8, Quantity = 3, UnitPrice = 42990m },
        new CustomerOrderItem { Id = 87, CustomerOrderId = 42, ProductId = 4, Quantity = 2, UnitPrice = 49990m },
        new CustomerOrderItem { Id = 88, CustomerOrderId = 43, ProductId = 18, Quantity = 15, UnitPrice = 3990m },
        new CustomerOrderItem { Id = 89, CustomerOrderId = 43, ProductId = 5, Quantity = 3, UnitPrice = 44990m },
        new CustomerOrderItem { Id = 90, CustomerOrderId = 44, ProductId = 15, Quantity = 2, UnitPrice = 44990m },
        new CustomerOrderItem { Id = 91, CustomerOrderId = 44, ProductId = 8, Quantity = 1, UnitPrice = 42990m },
        new CustomerOrderItem { Id = 92, CustomerOrderId = 44, ProductId = 2, Quantity = 1, UnitPrice = 34990m },
        new CustomerOrderItem { Id = 93, CustomerOrderId = 45, ProductId = 11, Quantity = 3, UnitPrice = 159990m },
        new CustomerOrderItem { Id = 94, CustomerOrderId = 45, ProductId = 20, Quantity = 1, UnitPrice = 109990m },
        new CustomerOrderItem { Id = 95, CustomerOrderId = 46, ProductId = 9, Quantity = 2, UnitPrice = 14990m },
        new CustomerOrderItem { Id = 96, CustomerOrderId = 46, ProductId = 12, Quantity = 6, UnitPrice = 24990m },
        new CustomerOrderItem { Id = 97, CustomerOrderId = 46, ProductId = 10, Quantity = 5, UnitPrice = 29990m },
        new CustomerOrderItem { Id = 98, CustomerOrderId = 46, ProductId = 1, Quantity = 3, UnitPrice = 39990m },
        new CustomerOrderItem { Id = 99, CustomerOrderId = 47, ProductId = 14, Quantity = 3, UnitPrice = 9990m },
        new CustomerOrderItem { Id = 100, CustomerOrderId = 47, ProductId = 6, Quantity = 3, UnitPrice = 5990m },
        new CustomerOrderItem { Id = 101, CustomerOrderId = 47, ProductId = 12, Quantity = 9, UnitPrice = 24990m },
        new CustomerOrderItem { Id = 102, CustomerOrderId = 47, ProductId = 10, Quantity = 3, UnitPrice = 29990m },
        new CustomerOrderItem { Id = 103, CustomerOrderId = 47, ProductId = 1, Quantity = 4, UnitPrice = 39990m },
        new CustomerOrderItem { Id = 104, CustomerOrderId = 48, ProductId = 9, Quantity = 2, UnitPrice = 14990m },
        new CustomerOrderItem { Id = 105, CustomerOrderId = 48, ProductId = 12, Quantity = 12, UnitPrice = 24990m },
        new CustomerOrderItem { Id = 106, CustomerOrderId = 48, ProductId = 10, Quantity = 4, UnitPrice = 29990m },
        new CustomerOrderItem { Id = 107, CustomerOrderId = 48, ProductId = 1, Quantity = 2, UnitPrice = 39990m },
        new CustomerOrderItem { Id = 108, CustomerOrderId = 49, ProductId = 1, Quantity = 6, UnitPrice = 39990m },
        new CustomerOrderItem { Id = 109, CustomerOrderId = 49, ProductId = 2, Quantity = 3, UnitPrice = 34990m },
        new CustomerOrderItem { Id = 110, CustomerOrderId = 49, ProductId = 12, Quantity = 8, UnitPrice = 24990m },
        new CustomerOrderItem { Id = 111, CustomerOrderId = 50, ProductId = 6, Quantity = 3, UnitPrice = 5990m },
        new CustomerOrderItem { Id = 112, CustomerOrderId = 50, ProductId = 12, Quantity = 10, UnitPrice = 24990m },
        new CustomerOrderItem { Id = 113, CustomerOrderId = 50, ProductId = 10, Quantity = 4, UnitPrice = 29990m },
    ];

    public static SupplierOrder[] SupplierOrders =>
    [
        new SupplierOrder { Id = 1, SupplierId = 1, OrderDate = new DateTime(2026, 9, 5, 8, 0, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new SupplierOrder { Id = 2, SupplierId = 2, OrderDate = new DateTime(2026, 9, 21, 10, 15, 0, DateTimeKind.Utc), Status = OrderStatus.Pending },
        new SupplierOrder { Id = 3, SupplierId = 3, OrderDate = new DateTime(2026, 8, 5, 9, 0, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new SupplierOrder { Id = 4, SupplierId = 4, OrderDate = new DateTime(2026, 8, 12, 13, 30, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new SupplierOrder { Id = 5, SupplierId = 1, OrderDate = new DateTime(2026, 8, 20, 10, 15, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new SupplierOrder { Id = 6, SupplierId = 2, OrderDate = new DateTime(2026, 9, 2, 8, 45, 0, DateTimeKind.Utc), Status = OrderStatus.Delivered },
        new SupplierOrder { Id = 7, SupplierId = 1, OrderDate = new DateTime(2026, 9, 29, 11, 0, 0, DateTimeKind.Utc), Status = OrderStatus.Shipped },
        new SupplierOrder { Id = 8, SupplierId = 4, OrderDate = new DateTime(2026, 10, 2, 14, 0, 0, DateTimeKind.Utc), Status = OrderStatus.Pending },
    ];

    public static SupplierOrderItem[] SupplierOrderItems =>
    [
        new SupplierOrderItem { Id = 1, SupplierOrderId = 1, ProductId = 1, Quantity = 20, UnitCost = 28000m },
        new SupplierOrderItem { Id = 2, SupplierOrderId = 1, ProductId = 4, Quantity = 10, UnitCost = 36000m },
        new SupplierOrderItem { Id = 3, SupplierOrderId = 2, ProductId = 8, Quantity = 5, UnitCost = 31000m },
        new SupplierOrderItem { Id = 4, SupplierOrderId = 2, ProductId = 7, Quantity = 10, UnitCost = 23500m },
        new SupplierOrderItem { Id = 5, SupplierOrderId = 3, ProductId = 17, Quantity = 500, UnitCost = 450m },
        new SupplierOrderItem { Id = 6, SupplierOrderId = 3, ProductId = 18, Quantity = 100, UnitCost = 1900m },
        new SupplierOrderItem { Id = 7, SupplierOrderId = 3, ProductId = 16, Quantity = 40, UnitCost = 7900m },
        new SupplierOrderItem { Id = 8, SupplierOrderId = 4, ProductId = 19, Quantity = 20, UnitCost = 27500m },
        new SupplierOrderItem { Id = 9, SupplierOrderId = 4, ProductId = 20, Quantity = 8, UnitCost = 79000m },
        new SupplierOrderItem { Id = 10, SupplierOrderId = 5, ProductId = 9, Quantity = 40, UnitCost = 9500m },
        new SupplierOrderItem { Id = 11, SupplierOrderId = 5, ProductId = 10, Quantity = 20, UnitCost = 19500m },
        new SupplierOrderItem { Id = 12, SupplierOrderId = 5, ProductId = 11, Quantity = 6, UnitCost = 115000m },
        new SupplierOrderItem { Id = 13, SupplierOrderId = 6, ProductId = 14, Quantity = 30, UnitCost = 6200m },
        new SupplierOrderItem { Id = 14, SupplierOrderId = 6, ProductId = 15, Quantity = 10, UnitCost = 31000m },
        new SupplierOrderItem { Id = 15, SupplierOrderId = 7, ProductId = 12, Quantity = 60, UnitCost = 16500m },
        new SupplierOrderItem { Id = 16, SupplierOrderId = 7, ProductId = 3, Quantity = 10, UnitCost = 76000m },
        new SupplierOrderItem { Id = 17, SupplierOrderId = 8, ProductId = 19, Quantity = 10, UnitCost = 27500m },
        new SupplierOrderItem { Id = 18, SupplierOrderId = 8, ProductId = 13, Quantity = 6, UnitCost = 64000m },
    ];

    // Kezdetben minden készlet a budapesti központi raktárban (Id = 1).
    // A 3-as terméknek nincs készlete, ezért nincs sora.
    public static Inventory[] Inventories =>
    [
        new Inventory { ProductId = 1, WarehouseId = 1, Quantity = 42 },
        new Inventory { ProductId = 2, WarehouseId = 1, Quantity = 6 },
        new Inventory { ProductId = 4, WarehouseId = 1, Quantity = 25 },
        new Inventory { ProductId = 5, WarehouseId = 1, Quantity = 12 },
        new Inventory { ProductId = 6, WarehouseId = 1, Quantity = 3 },
        new Inventory { ProductId = 7, WarehouseId = 1, Quantity = 18 },
        new Inventory { ProductId = 8, WarehouseId = 1, Quantity = 9 },
        new Inventory { ProductId = 9, WarehouseId = 1, Quantity = 35 },
        new Inventory { ProductId = 10, WarehouseId = 1, Quantity = 14 },
        new Inventory { ProductId = 11, WarehouseId = 1, Quantity = 4 },
        new Inventory { ProductId = 12, WarehouseId = 1, Quantity = 40 },
        new Inventory { ProductId = 13, WarehouseId = 1, Quantity = 7 },
        new Inventory { ProductId = 14, WarehouseId = 1, Quantity = 22 },
        new Inventory { ProductId = 15, WarehouseId = 1, Quantity = 6 },
        new Inventory { ProductId = 16, WarehouseId = 1, Quantity = 50 },
        new Inventory { ProductId = 17, WarehouseId = 1, Quantity = 300 },
        new Inventory { ProductId = 18, WarehouseId = 1, Quantity = 80 },
        new Inventory { ProductId = 19, WarehouseId = 1, Quantity = 18 },
        new Inventory { ProductId = 20, WarehouseId = 1, Quantity = 5 },
    ];
}
