// <auto-generated />
using System;
using IOMS.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IOMS.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260927113844_SeedDummyData")]
    partial class SeedDummyData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IOMS.DAL.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "anna.kovacs@example.com",
                            Name = "Kovács Anna",
                            Phone = "+36 30 111 2222"
                        },
                        new
                        {
                            Id = 2,
                            Email = "peter.nagy@example.com",
                            Name = "Nagy Péter",
                            Phone = "+36 20 333 4444"
                        },
                        new
                        {
                            Id = 3,
                            Email = "beszerzes@szabo-kft.example.com",
                            Name = "Szabó és Társa Kft."
                        });
                });

            modelBuilder.Entity("IOMS.DAL.Entities.CustomerOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            OrderDate = new DateTime(2026, 9, 1, 9, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 2,
                            OrderDate = new DateTime(2026, 9, 10, 14, 5, 0, 0, DateTimeKind.Utc),
                            Status = "Shipped"
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 3,
                            OrderDate = new DateTime(2026, 9, 20, 11, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 1,
                            OrderDate = new DateTime(2026, 9, 22, 16, 45, 0, 0, DateTimeKind.Utc),
                            Status = "Cancelled"
                        });
                });

            modelBuilder.Entity("IOMS.DAL.Entities.CustomerOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerOrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerOrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("CustomerOrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerOrderId = 1,
                            ProductId = 1,
                            Quantity = 2,
                            UnitPrice = 39990m
                        },
                        new
                        {
                            Id = 2,
                            CustomerOrderId = 1,
                            ProductId = 4,
                            Quantity = 1,
                            UnitPrice = 49990m
                        },
                        new
                        {
                            Id = 3,
                            CustomerOrderId = 2,
                            ProductId = 7,
                            Quantity = 1,
                            UnitPrice = 32990m
                        },
                        new
                        {
                            Id = 4,
                            CustomerOrderId = 2,
                            ProductId = 6,
                            Quantity = 5,
                            UnitPrice = 5990m
                        },
                        new
                        {
                            Id = 5,
                            CustomerOrderId = 3,
                            ProductId = 3,
                            Quantity = 3,
                            UnitPrice = 104990m
                        },
                        new
                        {
                            Id = 6,
                            CustomerOrderId = 3,
                            ProductId = 2,
                            Quantity = 3,
                            UnitPrice = 34990m
                        },
                        new
                        {
                            Id = 7,
                            CustomerOrderId = 3,
                            ProductId = 8,
                            Quantity = 2,
                            UnitPrice = 42990m
                        },
                        new
                        {
                            Id = 8,
                            CustomerOrderId = 4,
                            ProductId = 5,
                            Quantity = 2,
                            UnitPrice = 44990m
                        });
                });

            modelBuilder.Entity("IOMS.DAL.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MinStockLevel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Perifériák",
                            MinStockLevel = 10,
                            Name = "Logitech MX Master 3S egér",
                            Price = 39990m,
                            SKU = "PER-MX3S",
                            StockQuantity = 42
                        },
                        new
                        {
                            Id = 2,
                            Category = "Perifériák",
                            MinStockLevel = 8,
                            Name = "Keychron K2 billentyűzet",
                            Price = 34990m,
                            SKU = "PER-K2",
                            StockQuantity = 6
                        },
                        new
                        {
                            Id = 3,
                            Category = "Perifériák",
                            MinStockLevel = 5,
                            Name = "Dell P2723D 27\" monitor",
                            Price = 104990m,
                            SKU = "PER-P2723D",
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 4,
                            Category = "Tárolóeszközök",
                            MinStockLevel = 10,
                            Name = "Samsung 990 Pro 1TB SSD",
                            Price = 49990m,
                            SKU = "STO-990P-1T",
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 5,
                            Category = "Tárolóeszközök",
                            MinStockLevel = 6,
                            Name = "WD Red Plus 4TB HDD",
                            Price = 44990m,
                            SKU = "STO-WDRP-4T",
                            StockQuantity = 12
                        },
                        new
                        {
                            Id = 6,
                            Category = "Tárolóeszközök",
                            MinStockLevel = 15,
                            Name = "SanDisk Ultra 128GB pendrive",
                            Price = 5990m,
                            SKU = "STO-SDU-128",
                            StockQuantity = 3
                        },
                        new
                        {
                            Id = 7,
                            Category = "Hálózati eszközök",
                            MinStockLevel = 5,
                            Name = "TP-Link Archer AX55 router",
                            Price = 32990m,
                            SKU = "NET-AX55",
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 8,
                            Category = "Hálózati eszközök",
                            MinStockLevel = 4,
                            Name = "Ubiquiti UniFi Switch Lite 8",
                            Price = 42990m,
                            SKU = "NET-USL8",
                            StockQuantity = 9
                        });
                });

            modelBuilder.Entity("IOMS.DAL.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "rendeles@techdistri.example.com",
                            Name = "TechDistri Kft.",
                            Phone = "+36 1 555 1000"
                        },
                        new
                        {
                            Id = 2,
                            Email = "sales@netparts.example.com",
                            Name = "NetParts Zrt."
                        });
                });

            modelBuilder.Entity("IOMS.DAL.Entities.SupplierOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("SupplierOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderDate = new DateTime(2026, 9, 5, 8, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered",
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 2,
                            OrderDate = new DateTime(2026, 9, 21, 10, 15, 0, 0, DateTimeKind.Utc),
                            Status = "Pending",
                            SupplierId = 2
                        });
                });

            modelBuilder.Entity("IOMS.DAL.Entities.SupplierOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SupplierOrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SupplierOrderId");

                    b.ToTable("SupplierOrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            Quantity = 20,
                            SupplierOrderId = 1,
                            UnitCost = 28000m
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 4,
                            Quantity = 10,
                            SupplierOrderId = 1,
                            UnitCost = 36000m
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 8,
                            Quantity = 5,
                            SupplierOrderId = 2,
                            UnitCost = 31000m
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 7,
                            Quantity = 10,
                            SupplierOrderId = 2,
                            UnitCost = 23500m
                        });
                });

            modelBuilder.Entity("IOMS.DAL.Entities.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1117 Budapest, Példa utca 1.",
                            Capacity = 5000,
                            Latitude = 47.472999999999999,
                            Longitude = 19.053000000000001,
                            Name = "Budapesti központi raktár"
                        },
                        new
                        {
                            Id = 2,
                            Address = "4031 Debrecen, Minta út 12.",
                            Capacity = 2000,
                            Latitude = 47.531599999999997,
                            Longitude = 21.627300000000002,
                            Name = "Debreceni raktár"
                        });
                });

            modelBuilder.Entity("IOMS.DAL.Entities.CustomerOrder", b =>
                {
                    b.HasOne("IOMS.DAL.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("IOMS.DAL.Entities.CustomerOrderItem", b =>
                {
                    b.HasOne("IOMS.DAL.Entities.CustomerOrder", "CustomerOrder")
                        .WithMany("Items")
                        .HasForeignKey("CustomerOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IOMS.DAL.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CustomerOrder");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("IOMS.DAL.Entities.SupplierOrder", b =>
                {
                    b.HasOne("IOMS.DAL.Entities.Supplier", "Supplier")
                        .WithMany("Orders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("IOMS.DAL.Entities.SupplierOrderItem", b =>
                {
                    b.HasOne("IOMS.DAL.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IOMS.DAL.Entities.SupplierOrder", "SupplierOrder")
                        .WithMany("Items")
                        .HasForeignKey("SupplierOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("SupplierOrder");
                });

            modelBuilder.Entity("IOMS.DAL.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("IOMS.DAL.Entities.CustomerOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("IOMS.DAL.Entities.Supplier", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("IOMS.DAL.Entities.SupplierOrder", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
