// <auto-generated />
using System;
using IOMS.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IOMS.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261008202254_AddInventory")]
    partial class AddInventory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IOMS.DAL.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "anna.kovacs@example.com",
                            Name = "Kovács Anna",
                            Phone = "+36 30 111 2222"
                        },
                        new
                        {
                            Id = 2,
                            Email = "peter.nagy@example.com",
                            Name = "Nagy Péter",
                            Phone = "+36 20 333 4444"
                        },
                        new
                        {
                            Id = 3,
                            Email = "beszerzes@szabo-kft.example.com",
                            Name = "Szabó és Társa Kft."
                        },
                        new
                        {
                            Id = 4,
                            Email = "gabor.toth@example.com",
                            Name = "Tóth Gábor",
                            Phone = "+36 70 555 0101"
                        },
                        new
                        {
                            Id = 5,
                            Email = "eszter.horvath@example.com",
                            Name = "Horváth Eszter",
                            Phone = "+36 30 222 3344"
                        },
                        new
                        {
                            Id = 6,
                            Email = "bence.varga@example.com",
                            Name = "Varga Bence"
                        },
                        new
                        {
                            Id = 7,
                            Email = "iroda@kissesfia.example.com",
                            Name = "Kiss és Fia Bt.",
                            Phone = "+36 1 444 2020"
                        },
                        new
                        {
                            Id = 8,
                            Email = "reka.molnar@example.com",
                            Name = "Molnár Réka",
                            Phone = "+36 20 987 6543"
                        },
                        new
                        {
                            Id = 9,
                            Email = "laszlo.nemeth@example.com",
                            Name = "Németh László"
                        },
                        new
                        {
                            Id = 10,
                            Email = "beszerzes@digitalpro.example.com",
                            Name = "DigitalPro Zrt.",
                            Phone = "+36 1 777 8899"
                        },
                        new
                        {
                            Id = 11,
                            Email = "dora.farkas@example.com",
                            Name = "Farkas Dóra",
                            Phone = "+36 30 765 4321"
                        },
                        new
                        {
                            Id = 12,
                            Email = "info@balogh-it.example.com",
                            Name = "Balogh Informatika Kft.",
                            Phone = "+36 62 333 1100"
                        });
                });

            modelBuilder.Entity("IOMS.DAL.Entities.CustomerOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            OrderDate = new DateTime(2026, 9, 1, 9, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 2,
                            OrderDate = new DateTime(2026, 9, 10, 14, 5, 0, 0, DateTimeKind.Utc),
                            Status = "Shipped"
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 3,
                            OrderDate = new DateTime(2026, 9, 20, 11, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 1,
                            OrderDate = new DateTime(2026, 9, 22, 16, 45, 0, 0, DateTimeKind.Utc),
                            Status = "Cancelled"
                        },
                        new
                        {
                            Id = 5,
                            CustomerId = 1,
                            OrderDate = new DateTime(2026, 8, 1, 17, 45, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 6,
                            CustomerId = 5,
                            OrderDate = new DateTime(2026, 8, 2, 14, 15, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 7,
                            CustomerId = 2,
                            OrderDate = new DateTime(2026, 8, 4, 11, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 8,
                            CustomerId = 7,
                            OrderDate = new DateTime(2026, 8, 5, 13, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 9,
                            CustomerId = 5,
                            OrderDate = new DateTime(2026, 8, 7, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 10,
                            CustomerId = 1,
                            OrderDate = new DateTime(2026, 8, 8, 14, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 11,
                            CustomerId = 4,
                            OrderDate = new DateTime(2026, 8, 9, 17, 15, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 12,
                            CustomerId = 9,
                            OrderDate = new DateTime(2026, 8, 11, 8, 15, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 13,
                            CustomerId = 2,
                            OrderDate = new DateTime(2026, 8, 12, 11, 15, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 14,
                            CustomerId = 12,
                            OrderDate = new DateTime(2026, 8, 14, 15, 15, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 15,
                            CustomerId = 5,
                            OrderDate = new DateTime(2026, 8, 15, 11, 15, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 16,
                            CustomerId = 12,
                            OrderDate = new DateTime(2026, 8, 16, 8, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 17,
                            CustomerId = 4,
                            OrderDate = new DateTime(2026, 8, 17, 17, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 18,
                            CustomerId = 1,
                            OrderDate = new DateTime(2026, 8, 19, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 19,
                            CustomerId = 2,
                            OrderDate = new DateTime(2026, 8, 20, 10, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 20,
                            CustomerId = 5,
                            OrderDate = new DateTime(2026, 8, 22, 16, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 21,
                            CustomerId = 9,
                            OrderDate = new DateTime(2026, 8, 24, 10, 15, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 22,
                            CustomerId = 5,
                            OrderDate = new DateTime(2026, 8, 25, 11, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 23,
                            CustomerId = 8,
                            OrderDate = new DateTime(2026, 8, 26, 13, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 24,
                            CustomerId = 10,
                            OrderDate = new DateTime(2026, 8, 28, 8, 15, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 25,
                            CustomerId = 10,
                            OrderDate = new DateTime(2026, 8, 28, 18, 15, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 26,
                            CustomerId = 10,
                            OrderDate = new DateTime(2026, 8, 30, 10, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 27,
                            CustomerId = 11,
                            OrderDate = new DateTime(2026, 9, 1, 13, 45, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 28,
                            CustomerId = 12,
                            OrderDate = new DateTime(2026, 9, 2, 13, 15, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 29,
                            CustomerId = 11,
                            OrderDate = new DateTime(2026, 9, 3, 14, 15, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 30,
                            CustomerId = 4,
                            OrderDate = new DateTime(2026, 9, 4, 16, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 31,
                            CustomerId = 7,
                            OrderDate = new DateTime(2026, 9, 6, 9, 15, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 32,
                            CustomerId = 5,
                            OrderDate = new DateTime(2026, 9, 7, 16, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 33,
                            CustomerId = 11,
                            OrderDate = new DateTime(2026, 9, 9, 12, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 34,
                            CustomerId = 5,
                            OrderDate = new DateTime(2026, 9, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 35,
                            CustomerId = 8,
                            OrderDate = new DateTime(2026, 9, 12, 13, 15, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 36,
                            CustomerId = 7,
                            OrderDate = new DateTime(2026, 9, 13, 16, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Cancelled"
                        },
                        new
                        {
                            Id = 37,
                            CustomerId = 12,
                            OrderDate = new DateTime(2026, 9, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 38,
                            CustomerId = 2,
                            OrderDate = new DateTime(2026, 9, 16, 8, 45, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 39,
                            CustomerId = 3,
                            OrderDate = new DateTime(2026, 9, 17, 17, 15, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 40,
                            CustomerId = 5,
                            OrderDate = new DateTime(2026, 9, 19, 11, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 41,
                            CustomerId = 8,
                            OrderDate = new DateTime(2026, 9, 19, 14, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 42,
                            CustomerId = 4,
                            OrderDate = new DateTime(2026, 9, 21, 12, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 43,
                            CustomerId = 1,
                            OrderDate = new DateTime(2026, 9, 23, 11, 15, 0, 0, DateTimeKind.Utc),
                            Status = "Cancelled"
                        },
                        new
                        {
                            Id = 44,
                            CustomerId = 12,
                            OrderDate = new DateTime(2026, 9, 25, 8, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Shipped"
                        },
                        new
                        {
                            Id = 45,
                            CustomerId = 9,
                            OrderDate = new DateTime(2026, 9, 25, 15, 45, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 46,
                            CustomerId = 4,
                            OrderDate = new DateTime(2026, 9, 27, 14, 15, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 47,
                            CustomerId = 1,
                            OrderDate = new DateTime(2026, 9, 28, 9, 45, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = 48,
                            CustomerId = 6,
                            OrderDate = new DateTime(2026, 9, 30, 8, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Shipped"
                        },
                        new
                        {
                            Id = 49,
                            CustomerId = 11,
                            OrderDate = new DateTime(2026, 10, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 50,
                            CustomerId = 9,
                            OrderDate = new DateTime(2026, 10, 2, 18, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("IOMS.DAL.Entities.CustomerOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerOrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerOrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("CustomerOrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerOrderId = 1,
                            ProductId = 1,
                            Quantity = 2,
                            UnitPrice = 39990m
                        },
                        new
                        {
                            Id = 2,
                            CustomerOrderId = 1,
                            ProductId = 4,
                            Quantity = 1,
                            UnitPrice = 49990m
                        },
                        new
                        {
                            Id = 3,
                            CustomerOrderId = 2,
                            ProductId = 7,
                            Quantity = 1,
                            UnitPrice = 32990m
                        },
                        new
                        {
                            Id = 4,
                            CustomerOrderId = 2,
                            ProductId = 6,
                            Quantity = 5,
                            UnitPrice = 5990m
                        },
                        new
                        {
                            Id = 5,
                            CustomerOrderId = 3,
                            ProductId = 3,
                            Quantity = 3,
                            UnitPrice = 104990m
                        },
                        new
                        {
                            Id = 6,
                            CustomerOrderId = 3,
                            ProductId = 2,
                            Quantity = 3,
                            UnitPrice = 34990m
                        },
                        new
                        {
                            Id = 7,
                            CustomerOrderId = 3,
                            ProductId = 8,
                            Quantity = 2,
                            UnitPrice = 42990m
                        },
                        new
                        {
                            Id = 8,
                            CustomerOrderId = 4,
                            ProductId = 5,
                            Quantity = 2,
                            UnitPrice = 44990m
                        },
                        new
                        {
                            Id = 9,
                            CustomerOrderId = 5,
                            ProductId = 11,
                            Quantity = 3,
                            UnitPrice = 159990m
                        },
                        new
                        {
                            Id = 10,
                            CustomerOrderId = 5,
                            ProductId = 14,
                            Quantity = 2,
                            UnitPrice = 9990m
                        },
                        new
                        {
                            Id = 11,
                            CustomerOrderId = 5,
                            ProductId = 8,
                            Quantity = 1,
                            UnitPrice = 42990m
                        },
                        new
                        {
                            Id = 12,
                            CustomerOrderId = 6,
                            ProductId = 2,
                            Quantity = 3,
                            UnitPrice = 34990m
                        },
                        new
                        {
                            Id = 13,
                            CustomerOrderId = 6,
                            ProductId = 11,
                            Quantity = 2,
                            UnitPrice = 159990m
                        },
                        new
                        {
                            Id = 14,
                            CustomerOrderId = 6,
                            ProductId = 14,
                            Quantity = 2,
                            UnitPrice = 9990m
                        },
                        new
                        {
                            Id = 15,
                            CustomerOrderId = 7,
                            ProductId = 17,
                            Quantity = 12,
                            UnitPrice = 990m
                        },
                        new
                        {
                            Id = 16,
                            CustomerOrderId = 7,
                            ProductId = 12,
                            Quantity = 1,
                            UnitPrice = 24990m
                        },
                        new
                        {
                            Id = 17,
                            CustomerOrderId = 7,
                            ProductId = 10,
                            Quantity = 3,
                            UnitPrice = 29990m
                        },
                        new
                        {
                            Id = 18,
                            CustomerOrderId = 8,
                            ProductId = 8,
                            Quantity = 2,
                            UnitPrice = 42990m
                        },
                        new
                        {
                            Id = 19,
                            CustomerOrderId = 8,
                            ProductId = 5,
                            Quantity = 1,
                            UnitPrice = 44990m
                        },
                        new
                        {
                            Id = 20,
                            CustomerOrderId = 8,
                            ProductId = 7,
                            Quantity = 2,
                            UnitPrice = 32990m
                        },
                        new
                        {
                            Id = 21,
                            CustomerOrderId = 9,
                            ProductId = 2,
                            Quantity = 2,
                            UnitPrice = 34990m
                        },
                        new
                        {
                            Id = 22,
                            CustomerOrderId = 9,
                            ProductId = 20,
                            Quantity = 1,
                            UnitPrice = 109990m
                        },
                        new
                        {
                            Id = 23,
                            CustomerOrderId = 10,
                            ProductId = 5,
                            Quantity = 3,
                            UnitPrice = 44990m
                        },
                        new
                        {
                            Id = 24,
                            CustomerOrderId = 11,
                            ProductId = 6,
                            Quantity = 1,
                            UnitPrice = 5990m
                        },
                        new
                        {
                            Id = 25,
                            CustomerOrderId = 11,
                            ProductId = 8,
                            Quantity = 1,
                            UnitPrice = 42990m
                        },
                        new
                        {
                            Id = 26,
                            CustomerOrderId = 12,
                            ProductId = 5,
                            Quantity = 2,
                            UnitPrice = 44990m
                        },
                        new
                        {
                            Id = 27,
                            CustomerOrderId = 12,
                            ProductId = 13,
                            Quantity = 2,
                            UnitPrice = 89990m
                        },
                        new
                        {
                            Id = 28,
                            CustomerOrderId = 12,
                            ProductId = 6,
                            Quantity = 1,
                            UnitPrice = 5990m
                        },
                        new
                        {
                            Id = 29,
                            CustomerOrderId = 13,
                            ProductId = 5,
                            Quantity = 2,
                            UnitPrice = 44990m
                        },
                        new
                        {
                            Id = 30,
                            CustomerOrderId = 13,
                            ProductId = 20,
                            Quantity = 2,
                            UnitPrice = 109990m
                        },
                        new
                        {
                            Id = 31,
                            CustomerOrderId = 14,
                            ProductId = 10,
                            Quantity = 3,
                            UnitPrice = 29990m
                        },
                        new
                        {
                            Id = 32,
                            CustomerOrderId = 14,
                            ProductId = 6,
                            Quantity = 3,
                            UnitPrice = 5990m
                        },
                        new
                        {
                            Id = 33,
                            CustomerOrderId = 15,
                            ProductId = 14,
                            Quantity = 2,
                            UnitPrice = 9990m
                        },
                        new
                        {
                            Id = 34,
                            CustomerOrderId = 15,
                            ProductId = 11,
                            Quantity = 1,
                            UnitPrice = 159990m
                        },
                        new
                        {
                            Id = 35,
                            CustomerOrderId = 15,
                            ProductId = 15,
                            Quantity = 2,
                            UnitPrice = 44990m
                        },
                        new
                        {
                            Id = 36,
                            CustomerOrderId = 16,
                            ProductId = 15,
                            Quantity = 2,
                            UnitPrice = 44990m
                        },
                        new
                        {
                            Id = 37,
                            CustomerOrderId = 16,
                            ProductId = 19,
                            Quantity = 3,
                            UnitPrice = 39990m
                        },
                        new
                        {
                            Id = 38,
                            CustomerOrderId = 16,
                            ProductId = 16,
                            Quantity = 3,
                            UnitPrice = 12990m
                        },
                        new
                        {
                            Id = 39,
                            CustomerOrderId = 17,
                            ProductId = 7,
                            Quantity = 2,
                            UnitPrice = 32990m
                        },
                        new
                        {
                            Id = 40,
                            CustomerOrderId = 18,
                            ProductId = 16,
                            Quantity = 2,
                            UnitPrice = 12990m
                        },
                        new
                        {
                            Id = 41,
                            CustomerOrderId = 18,
                            ProductId = 20,
                            Quantity = 2,
                            UnitPrice = 109990m
                        },
                        new
                        {
                            Id = 42,
                            CustomerOrderId = 19,
                            ProductId = 10,
                            Quantity = 3,
                            UnitPrice = 29990m
                        },
                        new
                        {
                            Id = 43,
                            CustomerOrderId = 19,
                            ProductId = 11,
                            Quantity = 3,
                            UnitPrice = 159990m
                        },
                        new
                        {
                            Id = 44,
                            CustomerOrderId = 19,
                            ProductId = 9,
                            Quantity = 3,
                            UnitPrice = 14990m
                        },
                        new
                        {
                            Id = 45,
                            CustomerOrderId = 20,
                            ProductId = 15,
                            Quantity = 2,
                            UnitPrice = 44990m
                        },
                        new
                        {
                            Id = 46,
                            CustomerOrderId = 20,
                            ProductId = 18,
                            Quantity = 14,
                            UnitPrice = 3990m
                        },
                        new
                        {
                            Id = 47,
                            CustomerOrderId = 20,
                            ProductId = 17,
                            Quantity = 9,
                            UnitPrice = 990m
                        },
                        new
                        {
                            Id = 48,
                            CustomerOrderId = 21,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 34990m
                        },
                        new
                        {
                            Id = 49,
                            CustomerOrderId = 21,
                            ProductId = 18,
                            Quantity = 19,
                            UnitPrice = 3990m
                        },
                        new
                        {
                            Id = 50,
                            CustomerOrderId = 21,
                            ProductId = 10,
                            Quantity = 2,
                            UnitPrice = 29990m
                        },
                        new
                        {
                            Id = 51,
                            CustomerOrderId = 22,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 39990m
                        },
                        new
                        {
                            Id = 52,
                            CustomerOrderId = 22,
                            ProductId = 12,
                            Quantity = 1,
                            UnitPrice = 24990m
                        },
                        new
                        {
                            Id = 53,
                            CustomerOrderId = 23,
                            ProductId = 14,
                            Quantity = 3,
                            UnitPrice = 9990m
                        },
                        new
                        {
                            Id = 54,
                            CustomerOrderId = 23,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 39990m
                        },
                        new
                        {
                            Id = 55,
                            CustomerOrderId = 23,
                            ProductId = 6,
                            Quantity = 1,
                            UnitPrice = 5990m
                        },
                        new
                        {
                            Id = 56,
                            CustomerOrderId = 24,
                            ProductId = 19,
                            Quantity = 1,
                            UnitPrice = 39990m
                        },
                        new
                        {
                            Id = 57,
                            CustomerOrderId = 25,
                            ProductId = 18,
                            Quantity = 13,
                            UnitPrice = 3990m
                        },
                        new
                        {
                            Id = 58,
                            CustomerOrderId = 25,
                            ProductId = 1,
                            Quantity = 2,
                            UnitPrice = 39990m
                        },
                        new
                        {
                            Id = 59,
                            CustomerOrderId = 26,
                            ProductId = 11,
                            Quantity = 3,
                            UnitPrice = 159990m
                        },
                        new
                        {
                            Id = 60,
                            CustomerOrderId = 26,
                            ProductId = 19,
                            Quantity = 3,
                            UnitPrice = 39990m
                        },
                        new
                        {
                            Id = 61,
                            CustomerOrderId = 27,
                            ProductId = 1,
                            Quantity = 2,
                            UnitPrice = 39990m
                        },
                        new
                        {
                            Id = 62,
                            CustomerOrderId = 28,
                            ProductId = 8,
                            Quantity = 3,
                            UnitPrice = 42990m
                        },
                        new
                        {
                            Id = 63,
                            CustomerOrderId = 29,
                            ProductId = 7,
                            Quantity = 3,
                            UnitPrice = 32990m
                        },
                        new
                        {
                            Id = 64,
                            CustomerOrderId = 30,
                            ProductId = 7,
                            Quantity = 3,
                            UnitPrice = 32990m
                        },
                        new
                        {
                            Id = 65,
                            CustomerOrderId = 31,
                            ProductId = 8,
                            Quantity = 1,
                            UnitPrice = 42990m
                        },
                        new
                        {
                            Id = 66,
                            CustomerOrderId = 31,
                            ProductId = 6,
                            Quantity = 1,
                            UnitPrice = 5990m
                        },
                        new
                        {
                            Id = 67,
                            CustomerOrderId = 32,
                            ProductId = 13,
                            Quantity = 1,
                            UnitPrice = 89990m
                        },
                        new
                        {
                            Id = 68,
                            CustomerOrderId = 32,
                            ProductId = 15,
                            Quantity = 3,
                            UnitPrice = 44990m
                        },
                        new
                        {
                            Id = 69,
                            CustomerOrderId = 32,
                            ProductId = 11,
                            Quantity = 2,
                            UnitPrice = 159990m
                        },
                        new
                        {
                            Id = 70,
                            CustomerOrderId = 33,
                            ProductId = 18,
                            Quantity = 11,
                            UnitPrice = 3990m
                        },
                        new
                        {
                            Id = 71,
                            CustomerOrderId = 33,
                            ProductId = 16,
                            Quantity = 3,
                            UnitPrice = 12990m
                        },
                        new
                        {
                            Id = 72,
                            CustomerOrderId = 33,
                            ProductId = 4,
                            Quantity = 1,
                            UnitPrice = 49990m
                        },
                        new
                        {
                            Id = 73,
                            CustomerOrderId = 34,
                            ProductId = 1,
                            Quantity = 3,
                            UnitPrice = 39990m
                        },
                        new
                        {
                            Id = 74,
                            CustomerOrderId = 35,
                            ProductId = 14,
                            Quantity = 1,
                            UnitPrice = 9990m
                        },
                        new
                        {
                            Id = 75,
                            CustomerOrderId = 36,
                            ProductId = 6,
                            Quantity = 2,
                            UnitPrice = 5990m
                        },
                        new
                        {
                            Id = 76,
                            CustomerOrderId = 36,
                            ProductId = 5,
                            Quantity = 1,
                            UnitPrice = 44990m
                        },
                        new
                        {
                            Id = 77,
                            CustomerOrderId = 37,
                            ProductId = 11,
                            Quantity = 2,
                            UnitPrice = 159990m
                        },
                        new
                        {
                            Id = 78,
                            CustomerOrderId = 37,
                            ProductId = 17,
                            Quantity = 18,
                            UnitPrice = 990m
                        },
                        new
                        {
                            Id = 79,
                            CustomerOrderId = 37,
                            ProductId = 15,
                            Quantity = 1,
                            UnitPrice = 44990m
                        },
                        new
                        {
                            Id = 80,
                            CustomerOrderId = 38,
                            ProductId = 4,
                            Quantity = 3,
                            UnitPrice = 49990m
                        },
                        new
                        {
                            Id = 81,
                            CustomerOrderId = 38,
                            ProductId = 18,
                            Quantity = 11,
                            UnitPrice = 3990m
                        },
                        new
                        {
                            Id = 82,
                            CustomerOrderId = 38,
                            ProductId = 20,
                            Quantity = 3,
                            UnitPrice = 109990m
                        },
                        new
                        {
                            Id = 83,
                            CustomerOrderId = 39,
                            ProductId = 4,
                            Quantity = 3,
                            UnitPrice = 49990m
                        },
                        new
                        {
                            Id = 84,
                            CustomerOrderId = 40,
                            ProductId = 2,
                            Quantity = 2,
                            UnitPrice = 34990m
                        },
                        new
                        {
                            Id = 85,
                            CustomerOrderId = 40,
                            ProductId = 7,
                            Quantity = 1,
                            UnitPrice = 32990m
                        },
                        new
                        {
                            Id = 86,
                            CustomerOrderId = 41,
                            ProductId = 8,
                            Quantity = 3,
                            UnitPrice = 42990m
                        },
                        new
                        {
                            Id = 87,
                            CustomerOrderId = 42,
                            ProductId = 4,
                            Quantity = 2,
                            UnitPrice = 49990m
                        },
                        new
                        {
                            Id = 88,
                            CustomerOrderId = 43,
                            ProductId = 18,
                            Quantity = 15,
                            UnitPrice = 3990m
                        },
                        new
                        {
                            Id = 89,
                            CustomerOrderId = 43,
                            ProductId = 5,
                            Quantity = 3,
                            UnitPrice = 44990m
                        },
                        new
                        {
                            Id = 90,
                            CustomerOrderId = 44,
                            ProductId = 15,
                            Quantity = 2,
                            UnitPrice = 44990m
                        },
                        new
                        {
                            Id = 91,
                            CustomerOrderId = 44,
                            ProductId = 8,
                            Quantity = 1,
                            UnitPrice = 42990m
                        },
                        new
                        {
                            Id = 92,
                            CustomerOrderId = 44,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 34990m
                        },
                        new
                        {
                            Id = 93,
                            CustomerOrderId = 45,
                            ProductId = 11,
                            Quantity = 3,
                            UnitPrice = 159990m
                        },
                        new
                        {
                            Id = 94,
                            CustomerOrderId = 45,
                            ProductId = 20,
                            Quantity = 1,
                            UnitPrice = 109990m
                        },
                        new
                        {
                            Id = 95,
                            CustomerOrderId = 46,
                            ProductId = 9,
                            Quantity = 2,
                            UnitPrice = 14990m
                        },
                        new
                        {
                            Id = 96,
                            CustomerOrderId = 46,
                            ProductId = 12,
                            Quantity = 6,
                            UnitPrice = 24990m
                        },
                        new
                        {
                            Id = 97,
                            CustomerOrderId = 46,
                            ProductId = 10,
                            Quantity = 5,
                            UnitPrice = 29990m
                        },
                        new
                        {
                            Id = 98,
                            CustomerOrderId = 46,
                            ProductId = 1,
                            Quantity = 3,
                            UnitPrice = 39990m
                        },
                        new
                        {
                            Id = 99,
                            CustomerOrderId = 47,
                            ProductId = 14,
                            Quantity = 3,
                            UnitPrice = 9990m
                        },
                        new
                        {
                            Id = 100,
                            CustomerOrderId = 47,
                            ProductId = 6,
                            Quantity = 3,
                            UnitPrice = 5990m
                        },
                        new
                        {
                            Id = 101,
                            CustomerOrderId = 47,
                            ProductId = 12,
                            Quantity = 9,
                            UnitPrice = 24990m
                        },
                        new
                        {
                            Id = 102,
                            CustomerOrderId = 47,
                            ProductId = 10,
                            Quantity = 3,
                            UnitPrice = 29990m
                        },
                        new
                        {
                            Id = 103,
                            CustomerOrderId = 47,
                            ProductId = 1,
                            Quantity = 4,
                            UnitPrice = 39990m
                        },
                        new
                        {
                            Id = 104,
                            CustomerOrderId = 48,
                            ProductId = 9,
                            Quantity = 2,
                            UnitPrice = 14990m
                        },
                        new
                        {
                            Id = 105,
                            CustomerOrderId = 48,
                            ProductId = 12,
                            Quantity = 12,
                            UnitPrice = 24990m
                        },
                        new
                        {
                            Id = 106,
                            CustomerOrderId = 48,
                            ProductId = 10,
                            Quantity = 4,
                            UnitPrice = 29990m
                        },
                        new
                        {
                            Id = 107,
                            CustomerOrderId = 48,
                            ProductId = 1,
                            Quantity = 2,
                            UnitPrice = 39990m
                        },
                        new
                        {
                            Id = 108,
                            CustomerOrderId = 49,
                            ProductId = 1,
                            Quantity = 6,
                            UnitPrice = 39990m
                        },
                        new
                        {
                            Id = 109,
                            CustomerOrderId = 49,
                            ProductId = 2,
                            Quantity = 3,
                            UnitPrice = 34990m
                        },
                        new
                        {
                            Id = 110,
                            CustomerOrderId = 49,
                            ProductId = 12,
                            Quantity = 8,
                            UnitPrice = 24990m
                        },
                        new
                        {
                            Id = 111,
                            CustomerOrderId = 50,
                            ProductId = 6,
                            Quantity = 3,
                            UnitPrice = 5990m
                        },
                        new
                        {
                            Id = 112,
                            CustomerOrderId = 50,
                            ProductId = 12,
                            Quantity = 10,
                            UnitPrice = 24990m
                        },
                        new
                        {
                            Id = 113,
                            CustomerOrderId = 50,
                            ProductId = 10,
                            Quantity = 4,
                            UnitPrice = 29990m
                        });
                });

            modelBuilder.Entity("IOMS.DAL.Entities.Inventory", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "WarehouseId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Inventories", t =>
                        {
                            t.HasCheckConstraint("CK_Inventory_Quantity", "[Quantity] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            WarehouseId = 1,
                            Quantity = 42
                        },
                        new
                        {
                            ProductId = 2,
                            WarehouseId = 1,
                            Quantity = 6
                        },
                        new
                        {
                            ProductId = 4,
                            WarehouseId = 1,
                            Quantity = 25
                        },
                        new
                        {
                            ProductId = 5,
                            WarehouseId = 1,
                            Quantity = 12
                        },
                        new
                        {
                            ProductId = 6,
                            WarehouseId = 1,
                            Quantity = 3
                        },
                        new
                        {
                            ProductId = 7,
                            WarehouseId = 1,
                            Quantity = 18
                        },
                        new
                        {
                            ProductId = 8,
                            WarehouseId = 1,
                            Quantity = 9
                        },
                        new
                        {
                            ProductId = 9,
                            WarehouseId = 1,
                            Quantity = 35
                        },
                        new
                        {
                            ProductId = 10,
                            WarehouseId = 1,
                            Quantity = 14
                        },
                        new
                        {
                            ProductId = 11,
                            WarehouseId = 1,
                            Quantity = 4
                        },
                        new
                        {
                            ProductId = 12,
                            WarehouseId = 1,
                            Quantity = 40
                        },
                        new
                        {
                            ProductId = 13,
                            WarehouseId = 1,
                            Quantity = 7
                        },
                        new
                        {
                            ProductId = 14,
                            WarehouseId = 1,
                            Quantity = 22
                        },
                        new
                        {
                            ProductId = 15,
                            WarehouseId = 1,
                            Quantity = 6
                        },
                        new
                        {
                            ProductId = 16,
                            WarehouseId = 1,
                            Quantity = 50
                        },
                        new
                        {
                            ProductId = 17,
                            WarehouseId = 1,
                            Quantity = 300
                        },
                        new
                        {
                            ProductId = 18,
                            WarehouseId = 1,
                            Quantity = 80
                        },
                        new
                        {
                            ProductId = 19,
                            WarehouseId = 1,
                            Quantity = 18
                        },
                        new
                        {
                            ProductId = 20,
                            WarehouseId = 1,
                            Quantity = 5
                        });
                });

            modelBuilder.Entity("IOMS.DAL.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MinStockLevel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Perifériák",
                            MinStockLevel = 10,
                            Name = "Logitech MX Master 3S egér",
                            Price = 39990m,
                            SKU = "PER-MX3S",
                            StockQuantity = 42
                        },
                        new
                        {
                            Id = 2,
                            Category = "Perifériák",
                            MinStockLevel = 8,
                            Name = "Keychron K2 billentyűzet",
                            Price = 34990m,
                            SKU = "PER-K2",
                            StockQuantity = 6
                        },
                        new
                        {
                            Id = 3,
                            Category = "Perifériák",
                            MinStockLevel = 5,
                            Name = "Dell P2723D 27\" monitor",
                            Price = 104990m,
                            SKU = "PER-P2723D",
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 4,
                            Category = "Tárolóeszközök",
                            MinStockLevel = 10,
                            Name = "Samsung 990 Pro 1TB SSD",
                            Price = 49990m,
                            SKU = "STO-990P-1T",
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 5,
                            Category = "Tárolóeszközök",
                            MinStockLevel = 6,
                            Name = "WD Red Plus 4TB HDD",
                            Price = 44990m,
                            SKU = "STO-WDRP-4T",
                            StockQuantity = 12
                        },
                        new
                        {
                            Id = 6,
                            Category = "Tárolóeszközök",
                            MinStockLevel = 15,
                            Name = "SanDisk Ultra 128GB pendrive",
                            Price = 5990m,
                            SKU = "STO-SDU-128",
                            StockQuantity = 3
                        },
                        new
                        {
                            Id = 7,
                            Category = "Hálózati eszközök",
                            MinStockLevel = 5,
                            Name = "TP-Link Archer AX55 router",
                            Price = 32990m,
                            SKU = "NET-AX55",
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 8,
                            Category = "Hálózati eszközök",
                            MinStockLevel = 4,
                            Name = "Ubiquiti UniFi Switch Lite 8",
                            Price = 42990m,
                            SKU = "NET-USL8",
                            StockQuantity = 9
                        },
                        new
                        {
                            Id = 9,
                            Category = "Perifériák",
                            MinStockLevel = 10,
                            Name = "Logitech K380 billentyűzet",
                            Price = 14990m,
                            SKU = "PER-K380",
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 10,
                            Category = "Perifériák",
                            MinStockLevel = 6,
                            Name = "Razer DeathAdder V3 egér",
                            Price = 29990m,
                            SKU = "PER-DAV3",
                            StockQuantity = 14
                        },
                        new
                        {
                            Id = 11,
                            Category = "Perifériák",
                            MinStockLevel = 3,
                            Name = "LG 27GP850 27\" monitor",
                            Price = 159990m,
                            SKU = "PER-27GP850",
                            StockQuantity = 4
                        },
                        new
                        {
                            Id = 12,
                            Category = "Tárolóeszközök",
                            MinStockLevel = 15,
                            Name = "Kingston NV2 1TB SSD",
                            Price = 24990m,
                            SKU = "STO-NV2-1T",
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 13,
                            Category = "Tárolóeszközök",
                            MinStockLevel = 4,
                            Name = "Seagate IronWolf 8TB HDD",
                            Price = 89990m,
                            SKU = "STO-IW-8T",
                            StockQuantity = 7
                        },
                        new
                        {
                            Id = 14,
                            Category = "Hálózati eszközök",
                            MinStockLevel = 8,
                            Name = "TP-Link TL-SG108 switch",
                            Price = 9990m,
                            SKU = "NET-SG108",
                            StockQuantity = 22
                        },
                        new
                        {
                            Id = 15,
                            Category = "Hálózati eszközök",
                            MinStockLevel = 5,
                            Name = "Ubiquiti U6 Lite access point",
                            Price = 44990m,
                            SKU = "NET-U6L",
                            StockQuantity = 6
                        },
                        new
                        {
                            Id = 16,
                            Category = "Kábelek és adapterek",
                            MinStockLevel = 20,
                            Name = "UGREEN USB-C hub 7 az 1-ben",
                            Price = 12990m,
                            SKU = "KAB-UGH7",
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 17,
                            Category = "Kábelek és adapterek",
                            MinStockLevel = 100,
                            Name = "Cat6 patchkábel 2 m",
                            Price = 990m,
                            SKU = "KAB-CAT6-2",
                            StockQuantity = 300
                        },
                        new
                        {
                            Id = 18,
                            Category = "Kábelek és adapterek",
                            MinStockLevel = 30,
                            Name = "HDMI 2.1 kábel 2 m",
                            Price = 3990m,
                            SKU = "KAB-HDMI21",
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 19,
                            Category = "Számítógép-alkatrészek",
                            MinStockLevel = 6,
                            Name = "Corsair Vengeance 32GB DDR5",
                            Price = 39990m,
                            SKU = "ALK-CV32D5",
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 20,
                            Category = "Számítógép-alkatrészek",
                            MinStockLevel = 3,
                            Name = "AMD Ryzen 7 7700X processzor",
                            Price = 109990m,
                            SKU = "ALK-R77700X",
                            StockQuantity = 5
                        });
                });

            modelBuilder.Entity("IOMS.DAL.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "rendeles@techdistri.example.com",
                            Name = "TechDistri Kft.",
                            Phone = "+36 1 555 1000"
                        },
                        new
                        {
                            Id = 2,
                            Email = "sales@netparts.example.com",
                            Name = "NetParts Zrt."
                        },
                        new
                        {
                            Id = 3,
                            Email = "rendeles@kabelvilag.example.com",
                            Name = "Kábelvilág Kft.",
                            Phone = "+36 1 600 2500"
                        },
                        new
                        {
                            Id = 4,
                            Email = "info@alkatreszpont.example.com",
                            Name = "AlkatrészPont Bt."
                        });
                });

            modelBuilder.Entity("IOMS.DAL.Entities.SupplierOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("SupplierOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderDate = new DateTime(2026, 9, 5, 8, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered",
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 2,
                            OrderDate = new DateTime(2026, 9, 21, 10, 15, 0, 0, DateTimeKind.Utc),
                            Status = "Pending",
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 3,
                            OrderDate = new DateTime(2026, 8, 5, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered",
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 4,
                            OrderDate = new DateTime(2026, 8, 12, 13, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered",
                            SupplierId = 4
                        },
                        new
                        {
                            Id = 5,
                            OrderDate = new DateTime(2026, 8, 20, 10, 15, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered",
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 6,
                            OrderDate = new DateTime(2026, 9, 2, 8, 45, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered",
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 7,
                            OrderDate = new DateTime(2026, 9, 29, 11, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Shipped",
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 8,
                            OrderDate = new DateTime(2026, 10, 2, 14, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Pending",
                            SupplierId = 4
                        });
                });

            modelBuilder.Entity("IOMS.DAL.Entities.SupplierOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SupplierOrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SupplierOrderId");

                    b.ToTable("SupplierOrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            Quantity = 20,
                            SupplierOrderId = 1,
                            UnitCost = 28000m
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 4,
                            Quantity = 10,
                            SupplierOrderId = 1,
                            UnitCost = 36000m
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 8,
                            Quantity = 5,
                            SupplierOrderId = 2,
                            UnitCost = 31000m
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 7,
                            Quantity = 10,
                            SupplierOrderId = 2,
                            UnitCost = 23500m
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 17,
                            Quantity = 500,
                            SupplierOrderId = 3,
                            UnitCost = 450m
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 18,
                            Quantity = 100,
                            SupplierOrderId = 3,
                            UnitCost = 1900m
                        },
                        new
                        {
                            Id = 7,
                            ProductId = 16,
                            Quantity = 40,
                            SupplierOrderId = 3,
                            UnitCost = 7900m
                        },
                        new
                        {
                            Id = 8,
                            ProductId = 19,
                            Quantity = 20,
                            SupplierOrderId = 4,
                            UnitCost = 27500m
                        },
                        new
                        {
                            Id = 9,
                            ProductId = 20,
                            Quantity = 8,
                            SupplierOrderId = 4,
                            UnitCost = 79000m
                        },
                        new
                        {
                            Id = 10,
                            ProductId = 9,
                            Quantity = 40,
                            SupplierOrderId = 5,
                            UnitCost = 9500m
                        },
                        new
                        {
                            Id = 11,
                            ProductId = 10,
                            Quantity = 20,
                            SupplierOrderId = 5,
                            UnitCost = 19500m
                        },
                        new
                        {
                            Id = 12,
                            ProductId = 11,
                            Quantity = 6,
                            SupplierOrderId = 5,
                            UnitCost = 115000m
                        },
                        new
                        {
                            Id = 13,
                            ProductId = 14,
                            Quantity = 30,
                            SupplierOrderId = 6,
                            UnitCost = 6200m
                        },
                        new
                        {
                            Id = 14,
                            ProductId = 15,
                            Quantity = 10,
                            SupplierOrderId = 6,
                            UnitCost = 31000m
                        },
                        new
                        {
                            Id = 15,
                            ProductId = 12,
                            Quantity = 60,
                            SupplierOrderId = 7,
                            UnitCost = 16500m
                        },
                        new
                        {
                            Id = 16,
                            ProductId = 3,
                            Quantity = 10,
                            SupplierOrderId = 7,
                            UnitCost = 76000m
                        },
                        new
                        {
                            Id = 17,
                            ProductId = 19,
                            Quantity = 10,
                            SupplierOrderId = 8,
                            UnitCost = 27500m
                        },
                        new
                        {
                            Id = 18,
                            ProductId = 13,
                            Quantity = 6,
                            SupplierOrderId = 8,
                            UnitCost = 64000m
                        });
                });

            modelBuilder.Entity("IOMS.DAL.Entities.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1117 Budapest, Példa utca 1.",
                            Capacity = 5000,
                            Latitude = 47.472999999999999,
                            Longitude = 19.053000000000001,
                            Name = "Budapesti központi raktár"
                        },
                        new
                        {
                            Id = 2,
                            Address = "4031 Debrecen, Minta út 12.",
                            Capacity = 2000,
                            Latitude = 47.531599999999997,
                            Longitude = 21.627300000000002,
                            Name = "Debreceni raktár"
                        },
                        new
                        {
                            Id = 3,
                            Address = "9027 Győr, Ipari park 5.",
                            Capacity = 3000,
                            Latitude = 47.6875,
                            Longitude = 17.650400000000001,
                            Name = "Győri raktár"
                        },
                        new
                        {
                            Id = 4,
                            Address = "6728 Szeged, Logisztikai út 3.",
                            Capacity = 1500,
                            Latitude = 46.253,
                            Longitude = 20.141400000000001,
                            Name = "Szegedi raktár"
                        },
                        new
                        {
                            Id = 5,
                            Address = "7630 Pécs, Raktár utca 9.",
                            Capacity = 1200,
                            Latitude = 46.072699999999998,
                            Longitude = 18.232299999999999,
                            Name = "Pécsi raktár"
                        });
                });

            modelBuilder.Entity("IOMS.DAL.Entities.CustomerOrder", b =>
                {
                    b.HasOne("IOMS.DAL.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("IOMS.DAL.Entities.CustomerOrderItem", b =>
                {
                    b.HasOne("IOMS.DAL.Entities.CustomerOrder", "CustomerOrder")
                        .WithMany("Items")
                        .HasForeignKey("CustomerOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IOMS.DAL.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CustomerOrder");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("IOMS.DAL.Entities.Inventory", b =>
                {
                    b.HasOne("IOMS.DAL.Entities.Product", "Product")
                        .WithMany("Inventories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IOMS.DAL.Entities.Warehouse", "Warehouse")
                        .WithMany("Inventories")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("IOMS.DAL.Entities.SupplierOrder", b =>
                {
                    b.HasOne("IOMS.DAL.Entities.Supplier", "Supplier")
                        .WithMany("Orders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("IOMS.DAL.Entities.SupplierOrderItem", b =>
                {
                    b.HasOne("IOMS.DAL.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IOMS.DAL.Entities.SupplierOrder", "SupplierOrder")
                        .WithMany("Items")
                        .HasForeignKey("SupplierOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("SupplierOrder");
                });

            modelBuilder.Entity("IOMS.DAL.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("IOMS.DAL.Entities.CustomerOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("IOMS.DAL.Entities.Product", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("IOMS.DAL.Entities.Supplier", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("IOMS.DAL.Entities.SupplierOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("IOMS.DAL.Entities.Warehouse", b =>
                {
                    b.Navigation("Inventories");
                });
#pragma warning restore 612, 618
        }
    }
}
