// <auto-generated />
using IOMS.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IOMS.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260924154755_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IOMS.DAL.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MinStockLevel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Perifériák",
                            MinStockLevel = 10,
                            Name = "Logitech MX Master 3S Egér",
                            Price = 39900m,
                            SKU = "LOG-MX3S-BLK",
                            Status = "In Stock",
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 2,
                            Category = "Monitorok",
                            MinStockLevel = 5,
                            Name = "Dell UltraSharp U2723QE Monitor",
                            Price = 219000m,
                            SKU = "DEL-U2723QE",
                            Status = "Low Stock",
                            StockQuantity = 4
                        },
                        new
                        {
                            Id = 3,
                            Category = "Perifériák",
                            MinStockLevel = 8,
                            Name = "Keychron K2 Pro Mechanikus Billentyűzet",
                            Price = 45900m,
                            SKU = "KEY-K2PRO-RGB",
                            Status = "Out of Stock",
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 4,
                            Category = "Adattárolók",
                            MinStockLevel = 5,
                            Name = "Samsung 990 Pro 2TB NVMe SSD",
                            Price = 68900m,
                            SKU = "SAM-990PRO-2TB",
                            Status = "In Stock",
                            StockQuantity = 18
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
