@host = http://localhost:5150

GET {{host}}/api/products
Accept: application/json

###

GET {{host}}/api/products/1
Accept: application/json

###

# Eladási statisztika (csak a Delivered rendelések számítanak)
GET {{host}}/api/products/1/sales?from=2026-09-01&to=2026-09-30
Accept: application/json

###

GET {{host}}/api/warehouses
Accept: application/json

###

GET {{host}}/api/supplierorders
Accept: application/json

###

GET {{host}}/api/customers
Accept: application/json

###

GET {{host}}/api/customerorders
Accept: application/json

###

GET {{host}}/api/customerorderitems/by-order/1
Accept: application/json

###

POST {{host}}/api/customerorders
Content-Type: application/json

{
  "customerId": 1,
  "items": [
    { "productId": 1, "quantity": 2 },
    { "productId": 4, "quantity": 1 }
  ]
}

###
